openapi: 3.0.2
info:
  title: 'messageManager'
  version: '1.0.0'
paths:
  /manager/api/mailings:
    get:
      operationId: listMailingApis
      description: 'Get all mailings'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - manager
    post:
      operationId: createMailingApi
      description: 'Create new Mailing object with given parameters and schedule message sending'
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {
              "start_time": "2022-12-3 16:36:19",
              "text": "text",
              "filter_mobile_code": "915",
              "filter_tag": "tag",
              "end_time": "2023-12-3 16:36:19"
            }
            examples:
              request_data:
                value: {
                  "start_time": "2022-12-3 16:36:19",
                  "text": "text",
                  "filter_mobile_code": "915",
                  "filter_tag": "tag",
                  "end_time": "2023-12-3 16:36:19"
                }
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - manager
  /manager/api/mailing/{mailing_id}/:
    get:
      operationId: retrieveMailingItemApi
      description: 'Get mailing data by mailing id'
      parameters:
      - name: mailing_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {
                "id": 1,
                "start_time": "2022-12-03T16:36:19Z",
                "text": "text",
                "filter_mobile_code": "915",
                "filter_tag": "tag",
                "end_time": "2023-12-03T16:36:19Z",
                "celery_task_id": "task uuid"
              }
              examples:
                request_data:
                  value: {
                    "id": 1,
                    "start_time": "2022-12-03T16:36:19Z",
                    "text": "text",
                    "filter_mobile_code": "915",
                    "filter_tag": "tag",
                    "end_time": "2023-12-03T16:36:19Z",
                    "celery_task_id": "task uuid"
                  }
          description: ''
      tags:
      - manager
    put:
      operationId: updateMailingItemApi
      description: 'Modify mailing data by mailing id, stop current message sending and re-schedule it'
      parameters:
      - name: mailing_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {
              "start_time": "2022-12-3 16:36:19",
              "text": "text",
              "filter_mobile_code": "915",
              "filter_tag": "tag",
              "end_time": "2023-12-3 16:36:19"
            }
            examples:
              request_data:
                value: {
                  "start_time": "2022-12-3 16:36:19",
                  "text": "text",
                  "filter_mobile_code": "915",
                  "filter_tag": "tag",
                  "end_time": "2023-12-3 16:36:19"
                }
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - manager
    delete:
      operationId: destroyMailingItemApi
      description: 'Delete Mailing object, stop mailing'
      parameters:
      - name: mailing_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - manager
  /manager/api/clients:
    get:
      operationId: listClientApis
      description: 'Get all clients'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - manager
    post:
      operationId: createClientApi
      description: 'Add new client'
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {
              "phone": "79150000000",
              "mobile_code": "915",
              "tag": "tag",
              "timezone": "Europe/Amsterdam"
            }
            examples:
              request_data:
                value: {
                  "phone": "79150000000",
                  "mobile_code": "915",
                  "tag": "tag",
                  "timezone": "Europe/Amsterdam"
                }
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - manager
  /manager/api/client/{client_id}/:
    get:
      operationId: retrieveClientItemApi
      description: 'Get client data by client id'
      parameters:
        - name: client_id
          in: path
          required: true
          description: ''
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema: { }
          description: ''
      tags:
        - manager
    put:
      operationId: updateClientItemApi
      description: 'Modify client data by client id'
      parameters:
        - name: client_id
          in: path
          required: true
          description: ''
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema: {
              "phone": "79150000000",
              "mobile_code": "915",
              "tag": "tag",
              "timezone": "Europe/Amsterdam"
            }
            examples:
              request_data:
                value: {
                  "phone": "79150000000",
                  "mobile_code": "915",
                  "tag": "tag",
                  "timezone": "Europe/Amsterdam"
                }
          application/x-www-form-urlencoded:
            schema: { }
          multipart/form-data:
            schema: { }
      responses:
        '200':
          content:
            application/json:
              schema: { }
          description: ''
      tags:
        - manager
    delete:
      operationId: destroyClientItemApi
      description: 'Delete client from database by client id'
      parameters:
        - name: client_id
          in: path
          required: true
          description: ''
          schema:
            type: string
      responses:
        '204':
          description: ''
      tags:
        - manager
  /manager/api/messages:
    get:
      operationId: listMessageApis
      description: 'Get all messages'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - manager
