# Generated by Django 4.1.3 on 2022-12-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11)),
                ('mobile_code', models.CharField(max_length=3)),
                ('tag', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True)),
                ('text', models.CharField(max_length=500)),
                ('filter', models.CharField(max_length=50)),
                ('end_time', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('send_time', models.DateTimeField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('id_mailing', models.IntegerField()),
                ('id_client', models.IntegerField()),
            ],
        ),
    ]
